name: rtu_app_core
description: A set of utilities, themes and components for RTU MIREA applications by Mirea Ninja.
homepage: https://github.com/mirea-ninja/rtu-app-core
version: 0.0.3

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  unicons: any
  flutter_platform_widgets: ^3.3.4
  cupertino_list_tile: ^0.2.1
  flutter_svg: ^2.0.6
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/SFProDisplay-Heavy.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/SFProDisplay-UltralightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/SFProDisplay-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/SFProDisplay-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/SFProDisplay-Light.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/SFProDisplay-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/SFProDisplay-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/SFProDisplay-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/SFProDisplay-Ultralight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/SFProDisplay-LightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/SFProDisplay-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/SFProDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/SFProDisplay-HeavyItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/SFProDisplay-BoldItalic.ttf
          style: italic
          weight: 700
